// Generated by the WOLips Templateengine Plug-in at 1 sept. 2011 15:25:17
package org.cocktail.datte;

import org.cocktail.datte.pojo.EvenementPojo;
import org.cocktail.fwkcktlajaxwebext.serveur.CocktailAjaxSession;

import com.webobjects.appserver.WOActionResults;
import com.webobjects.foundation.NSDictionary;
import com.webobjects.foundation.NSMutableArray;

public class Session extends CocktailAjaxSession {
	private static final long serialVersionUID = 1L;
	private String messageErreur;
	private DatteApplicationUser applicationUser;
	private EvenementPojo event;
	private NSMutableArray<EvenementPojo> reservations;

	public Session() {
	}
	public WOActionResults onQuitter() {
		return logout();
	}

	public void reset() {
		if (defaultEditingContext() != null) {
			defaultEditingContext().revert();
		}
	}
	public NSDictionary<?, ?> exceptionInfos() {
		return null;
	}

	public DatteApplicationUser applicationUser() {
		return applicationUser;
	}
	public void setApplicationUser(DatteApplicationUser appUser) {
		this.applicationUser=appUser;		
	}

	public boolean isEtudiant() {
		return applicationUser.isEtudiant();
	}

	public boolean isGestionnaire() {
		return applicationUser.isGestionnaire();
	}

	public boolean isAutorise() {
//		System.out.println("N° individu : " + applicationUser.getNoIndividu());
		return isGestionnaire();
		// Dans le cas où l'application serait utilisé en remplacement de PriseDeRendezVousT5 
		// return isGestionnaire() || isEtudiant();
	}
	
	/**
	 * @return the messageErreur
	 */
	public String messageErreur() {
		return messageErreur;
	}

	public void setMessageErreur(String messageErreur) {
		this.messageErreur = messageErreur;
	}
	public void setEvent(EvenementPojo event) {
		this.event = event;
	}

	public EvenementPojo getEvent() {
		return event;
	}
	public NSMutableArray<EvenementPojo> getReservations() {
		return reservations;
	}
	public void setReservations(NSMutableArray<EvenementPojo> reservations) {
		this.reservations = reservations;
	}
	
}
